require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CommentariesController do

  def mock_commentary(stubs={})
    @mock_commentary ||= mock_model(Commentary, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all commentaries as @commentaries" do
      Commentary.stub(:all) { [mock_commentary] }
      get :index
      assigns(:commentaries).should eq([mock_commentary])
    end
  end

  describe "GET show" do
    it "assigns the requested commentary as @commentary" do
      Commentary.stub(:find).with("37") { mock_commentary }
      get :show, :id => "37"
      assigns(:commentary).should be(mock_commentary)
    end
  end

  describe "GET new" do
    it "assigns a new commentary as @commentary" do
      Commentary.stub(:new) { mock_commentary }
      get :new
      assigns(:commentary).should be(mock_commentary)
    end
  end

  describe "GET edit" do
    it "assigns the requested commentary as @commentary" do
      Commentary.stub(:find).with("37") { mock_commentary }
      get :edit, :id => "37"
      assigns(:commentary).should be(mock_commentary)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created commentary as @commentary" do
        Commentary.stub(:new).with({'these' => 'params'}) { mock_commentary(:save => true) }
        post :create, :commentary => {'these' => 'params'}
        assigns(:commentary).should be(mock_commentary)
      end

      it "redirects to the created commentary" do
        Commentary.stub(:new) { mock_commentary(:save => true) }
        post :create, :commentary => {}
        response.should redirect_to(commentary_url(mock_commentary))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved commentary as @commentary" do
        Commentary.stub(:new).with({'these' => 'params'}) { mock_commentary(:save => false) }
        post :create, :commentary => {'these' => 'params'}
        assigns(:commentary).should be(mock_commentary)
      end

      it "re-renders the 'new' template" do
        Commentary.stub(:new) { mock_commentary(:save => false) }
        post :create, :commentary => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested commentary" do
        Commentary.stub(:find).with("37") { mock_commentary }
        mock_commentary.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :commentary => {'these' => 'params'}
      end

      it "assigns the requested commentary as @commentary" do
        Commentary.stub(:find) { mock_commentary(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:commentary).should be(mock_commentary)
      end

      it "redirects to the commentary" do
        Commentary.stub(:find) { mock_commentary(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(commentary_url(mock_commentary))
      end
    end

    describe "with invalid params" do
      it "assigns the commentary as @commentary" do
        Commentary.stub(:find) { mock_commentary(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:commentary).should be(mock_commentary)
      end

      it "re-renders the 'edit' template" do
        Commentary.stub(:find) { mock_commentary(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested commentary" do
      Commentary.stub(:find).with("37") { mock_commentary }
      mock_commentary.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the commentaries list" do
      Commentary.stub(:find) { mock_commentary }
      delete :destroy, :id => "1"
      response.should redirect_to(commentaries_url)
    end
  end

end
